# Generated by Django 3.2.3 on 2021-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
            ],
            options={
                'verbose_name': 'shipping',
                'verbose_name_plural': 'Shippings',
                'db_table': 'shipping',
            },
        ),
    ]
